### ISSUE TITLE
Using the `php-tui` vendor on packagist.org .. ?

### ISSUE THREAD

**Issue by dantleech** [bgreenacre/php-tui#1]
Hi :wave: 

I recently started a `php-tui` project based on the Rust TUI/Ratatui library: https://github.com/php-tui/php-tui it also includes ports of the Casswary layout algorthim and Crossterm (more or less)

It's reasonably well advanced now, although not yet released.

Would you consider yielding the `php-tui` vendor on packagist.org? I currently have `phptui` [link](https://packagist.org/packages/phptui/cassowary) but it would be nice if it matched the `php-tui` github org.

If you still have plans for this package then no problem!

Cheers!

Dan

**Comment by bgreenacre** [comment]
Done.

**Comment by dantleech** [comment]
Thanks!
